apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app: {{.Values.name}}
  name: {{.Values.name}}
data:
  {{- range $key, $key_value := .Values.EnvsConfigMap}} 
  {{$key}}: {{$key_value}}
  {{- end}}
